### ISSUE TITLE
How do you unpack a text file?

### ISSUE THREAD

**Issue by Touch-XD** [Arikatsu/WW_Data#2]
How do you unpack a text file? Do you have a way to unpack and repack it? I would like to translate the game wuthering wave into my local language. Can you help?

**Comment by Touch-XD** [comment]
I come from the Thailand mod community. Now I want to translate just some of the game's content to make the game more fun to play. If you know please help us.

**Comment by Arikatsu** [comment]
text files are easy, just connect directly to the db and dump it in your preferred format

**Comment by codename0og** [comment]
@Touch-XD Yo~
Did you figure out the translation?
I'm actually trying to do a similar thing and any info would be appreciated!
