### ISSUE TITLE
Characters and Multipliers for Demage Report Tool

### ISSUE THREAD

**Issue by christophschoeni** [Arikatsu/WW_Data#3]
Hello Arikatsu

I help a young apprentice with his first Python project. He wants to develop a demage report tool in Python and needs the respective multiplier data of the respective characters. Before he goes to the trouble of developing a scrapper, I wanted to ask your ingenious project whether this data is already available from you. 

Best regards and many thanks
Christoph

**Comment by Arikatsu** [comment]
Do you need how the damage is calculated or individual damage multipliers of their forte skills for each character?

**Comment by jdevang** [comment]
Do you know the location of the damage formula + the locations for the multipliers and base atk of the resonators?

**Comment by flysand7** [comment]
@Arikatsu It would be helpful to know where the damage multipliers of forte skills, and other data like base stats for resonators and weapons are located.

**Comment by alt3ri** [comment]
> @Arikatsu It would be helpful to know where the damage multipliers of forte skills, and other data like base stats for resonators and weapons are located.

find baseproperty.json, with matched ID with character (rolepropertygrowth.json) and weapon (weaponpropertygrowth.json), for skills you just need to focus on skilllevel.json, skill.json, skilltype.json, skilldescription.json, damage.json (if you want damage table)

**Comment by flysand7** [comment]
Thanks! I believe the issue can be closed now
