### ISSUE TITLE
cbt1?

### ISSUE THREAD

**Issue by sergito-45** [Arikatsu/WW_Data#7]
Is there a repository like this for CBT1? 
and is there a way to get the CBT1 game files for datamining purposes?

**Comment by alt3ri** [comment]
https://github.com/Arikatsu/WutheringWaves_Data/tree/0.7

**Comment by sergito-45** [comment]
thanks :) this doesnt work for textures and 3d models right? is there another way to acces those?

**Comment by Arikatsu** [comment]
They are extractable but you'll need the client

**Comment by sergito-45** [comment]
yeah I want the client but couldnt find it, if you know how to get it pls let me know
